### PR TITLE
Final merge ready

### PR DESCRIPTION
**Pull request by rishabhborn2win**

### CODE REVIEW

**Review by Devanshi-123 — CHANGES_REQUESTED** [review]
Add these components in app.js

**Review by Devanshi-123 — APPROVED** [review]

**Review by divyaprakash-Rx — CHANGES_REQUESTED** [review]
@rishabhborn2win , you have got some issues while syncing with master, rectify using browser developer tools.

**Comment by rishabhborn2win** [comment]
> @rishabhborn2win , you have got some issues while syncing with master, rectify using browser developer tools

Modules error is showing.

**Comment by divyaprakash-Rx** [comment]
> 
> Modules error is showing.
The carousel you are using uses jquery, 
That is the module which is missing.
Add it to rectify the error.

**Pull request merged**
