### PR TITLE
Added Video Popup component

### PR DESCRIPTION
**Pull request by PalakKumari**
added component files, modified app.js and package.json(added react player dependency)

### CODE REVIEW

**Comment by PalakKumari** [comment]
screenshot-videopopup

**Comment by raksh543** [comment]
@PalakKumari It is not getting closed on clicking on cross
Also make the background colour white instead of brown colour used.

**Comment by PalakKumari** [comment]
I’ll do it but it might take some time because I am learning basics of  Javascript . Sent from Mail for Windows 10 From: Rakshita JainSent: Thursday, November 5, 2020 7:53 PMTo: dscnitp/ngo-donations-siteCc: Palak Kumari; MentionSubject: Re: [dscnitp/ngo-donations-site] Added Video Popup component (#46) @PalakKumari It is not getting closed on clicking on crossAlso make the background colour white instead of brown colour used.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by raksh543** [comment]
@PalakKumari Please complete the changes requested.

**Pull request closed without merging**
