### PR TITLE
signup (ind+org) looking for help BackEnd

### PR DESCRIPTION
**Pull request by Vishal559**

### CODE REVIEW

**Comment by raksh543** [comment]
Please resolve your CodeQL errors @Rupali0311(rating.js) @AdityaGupta150(app.js)

**Comment by AdityaGupta150** [comment]
> Please resolve your CodeQL errors @Rupali0311(rating.js) @AdityaGupta150(app.js)

Mam the codeql error for rate limiting is already solved in the dscnitp/master branch's app.js

https://github.com/dscnitp/ngo-donations-site/blob/4f26872a64f92807ac9558213bd4d4257b737bc8/server/app.js#L46-L51


Will try to merge it 👍🏽

**Comment by Rupali0311** [comment]
But Rakshita, rating.js has already been merged i guess and all checks were
passed when i created the pull request.

**Comment by AdityaGupta150** [comment]
@raksh543 Mam the merge conflicts in `app.js` and `.gitignore` has been resolved in commit https://github.com/AdityaGupta150/ngo-donations-site/commit/141ed2593e67333f1682e3bcbee808eb28bf98f0 , and .env removed.

As for the codeql error for rate limiting, NOT SURE BUT it maybe due to the additional lines between `app.use("/someRoute", <someRouter>);` statements may not have been understood, if they are read correctly then rate limiting should automatically apply to the user.js too.

https://github.com/Vishal559/ngo-donations-site/blob/95ad44e2c2ee56c4fe6ee62682cbd1e5ee8a5b7a/server/app.js#L80-L94


I also added yarn.lock to .gitignore for now, it was also giving merge conflicts in some commits.
Should it be removed from gitignore ?

@Vishal559 Please solve the other file conflicts in the other files that you may have modified, there are too many conflicts 😞

**Comment by AdityaGupta150** [comment]
@Vishal559 There are more file conflicts still remaining in some files, so the PR shouldn't be merged now, even if the checks passed

**Comment by AdityaGupta150** [comment]
This PR will be failing the tests after #56 is merged. File conflicts need to be solved for server to run.

**Pull request closed without merging**
