### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by arnav1507**
-Card width decreased
-customized tag names

### CODE REVIEW

**Review by Devanshi-123 — APPROVED** [review]

**Review by Devanshi-123 — CHANGES_REQUESTED** [review]
There is some issue with the orientation of events rectify it

**Comment by raksh543** [comment]
@arnav1507 Please solve this issue.
image

**Comment by arnav1507** [comment]
> @arnav1507 Please solve this issue.
> image

@raksh543 ma'am, this issue was coming because aastha has used container keyword in her styling. Devanshi ma'am has asked her to change that.

**Comment by arnav1507** [comment]
@raksh543 @Devanshi-123 ma'am, now also it is not coming properly because some people are using keywords in their css.
Screenshot (889)
Screenshot (890)

**Comment by raksh543** [comment]
@arnav1507 Is this running fine on your local machine?
As far as i noticed, the div styling is yours only so can you tell which css styling is over riding your elements' styling so that we can get that rectified?

**Comment by arnav1507** [comment]
> @arnav1507 Is this running fine on your local machine?
> As far as i noticed, the div styling is yours only so can you tell which css styling is over riding your elements' styling so that we can get that rectified?

yes @raksh543 ma'am, it is running fine in my local system. I have added snapshots of page in my local below. And no ma'am I have not used any keywords in my styling. That card-body, row and other keywords that are disturbing my page don't belong to my css😅.
Screenshot (902)
Screenshot (898)
Screenshot (899)
Screenshot (900)
Screenshot (901)

**Comment by raksh543** [comment]
@arnav1507 Create a PR on branch "rakshita".

**Comment by arnav1507** [comment]
> @arnav1507 Create a PR on branch "rakshita".

okay

**Pull request closed without merging**
