### PR TITLE
Event Page Added

### PR DESCRIPTION
**Pull request by arnav1507**
Screenshot (842)
Screenshot (843)
Screenshot (846)
Screenshot (847)

### CODE REVIEW

**Review by divyaprakash-Rx — CHANGES_REQUESTED** [review]
@arnav1507 Please check and correct the responsiveness for the page components.

**Comment by arnav1507** [comment]
> @arnav1507 Please check and correct the responsiveness for the page components.

Ya, i edited the files to make it more responsive. Please check it ones @divyaprakash-Rx

**Review by divyaprakash-Rx — CHANGES_REQUESTED** [review]
@arnav1507 Good Job! But these are some places that need your attentions.
Please check and modify accordingly.

- [ ] The cards should be of a standard size,placed in center of screen and justified accordingly.
- [x] The Two different columns should not overlap.
- [x] The upper background picture should not be stretched but maintain its original ratio.
 I have added some of the screenshots for your reference.
- [x] In search input, the text alignment is at center, please make it left aligned with some paddings.
Screen Shot 2020-10-18 at 21 31 43

Screen Shot 2020-10-18 at 21 22 51

Screen Shot 2020-10-18 at 21 22 33

Screen Shot 2020-10-18 at 21 23 07

Screen Shot 2020-10-18 at 21 23 02

**Review by Devanshi-123 — CHANGES_REQUESTED** [review]
Instead of making changes to app.js can you make a separate file event.js and then import it in app.js

**Comment by arnav1507** [comment]
> Instead of making changes to app.js can you make a separate file event.js and then import it in app.js

Done @Devanshi-123 Ma'am

**Review by divyaprakash-Rx — CHANGES_REQUESTED** [review]
@arnav1507 I have sorted out your issues with cards.
Please move your files in src/components/event folder.
Please sync your fork with master branch of main repo before proceeding further.

**Comment by raksh543** [comment]
> @arnav1507 I have sorted out your issues with cards.
> Please move your files in src/components/event folder.
> Please sync your fork with master branch of main repo before proceeding further.

@divyaprakash-Rx Components view is now not as expected in chrome or edge browser. Please revert your changes or rectify the issue.

**Comment by divyaprakash-Rx** [comment]
> 
> @divyaprakash-Rx Components view is now not as expected in chrome or edge browser. Please revert your changes or rectify the issue.

@raksh543 mam, arnav is working on the components now. This PR is not complete now. I am helping him sorting the code issues.

**Comment by raksh543** [comment]
@arnav1507 Please provide the status of the task.

**Comment by arnav1507** [comment]
> @arnav1507 Please provide the status of the task.

@raksh543 ma'am, i am trying to rectify this since last 2-3 days, i have tried many changes but it's still the same. If something goes ok other things don't. I have also tried the changes divya has suggested but it's still the same. I don't know what to do now

**Comment by arnav1507** [comment]
**The site was much better before the changes were made.** 
Screenshot (874)
Screenshot (875)
Screenshot (876)
Screenshot (877)

**Comment by divyaprakash-Rx** [comment]
> 
> 
> **The site was much better before the changes were made.**
@arnav1507 I have reset your PR to your previous one. Now, please rectify your errors.

**Review by Devanshi-123 — APPROVED** [review]

**Review by divyaprakash-Rx — CHANGES_REQUESTED** [review]
@arnav1507 Please don't style using tags or alter the default styling classes provided by any libraries.
At that place, use your custom classes so that it does not matches to any other one in this project.

**Comment by arnav1507** [comment]
> @arnav1507 Please don't style using tags or alter the default styling classes provided by any libraries.
> 
> At that place, use your custom classes so that it does not matches to any other one in this project.
> 
> Also,please reduce the size of cards for screen size of width smaller than 600px.

Okay

**Comment by raksh543** [comment]
Closing this PR as other PR is active now.

**Pull request closed without merging**
