### PR TITLE
Added Homepage Components

### PR DESCRIPTION
**Pull request by rishabhborn2win**
Added the point for NGO Platform of surfing feeds which can show the active state of the organisation.

### CODE REVIEW

**Comment by rishabhborn2win** [comment]
About Us and rating component Added

**Comment by rishabhborn2win** [comment]
Added 4 components
book
rating
cause
top stories

**Comment by raksh543** [comment]
@rishabhborn2win Please add screenshots as well.

**Comment by rishabhborn2win** [comment]
image
image
image
image

**Comment by rishabhborn2win** [comment]
updating all the errors and creating a new PR.

**Pull request closed without merging**
