### PR TITLE
Added FAQ page frontend

### PR DESCRIPTION
**Pull request by vikhyatsingh123**
I completed my task by adding FAQ page.

### CODE REVIEW

**Comment by raksh543** [comment]
@vikhyatsingh123 Please add screenshots as well.

**Comment by vikhyatsingh123** [comment]
@raksh543 Screenshot of FAQ page

https://user-images.githubusercontent.com/57625505/96349557-106fc580-10ce-11eb-9342-67c58652ec75.png

**Review by Devanshi-123 — CHANGES_REQUESTED** [review]
Change filename to Faq.js and import it to app.js

**Comment by raksh543** [comment]
@vikhyatsingh123 Also make your accordion drop down to show answer. Answer will not be shown in same line as question.

image

**Comment by raksh543** [comment]
Closing this PR as other PR is active now.

**Pull request closed without merging**
