### PR TITLE
added sign up page

### PR DESCRIPTION
**Pull request by AasthaSinha2305**
one

two

three

four

main sign up page with four different other signup pages depending on the user.

### CODE REVIEW

**Comment by raksh543** [comment]
@AasthaSinha2305 Great work!
Please change the name of Sign1, Sign2, Sign3, Sign4 to some specific name so that they can be identified easily.

**Review by divyaprakash-Rx — CHANGES_REQUESTED** [review]
@AasthaSinha2305 please log the form values till the api is provided.

**Comment by AasthaSinha2305** [comment]
@raksh543 @divyaprakash-Rx 
All the requested changes had been done from my side please verify...and let me know if any further changes are required....

**Review by divyaprakash-Rx — CHANGES_REQUESTED** [review]
@AasthaSinha2305 
 - [ ] Log form values, not confirmation.
e.g. onSubmit -> console.log() should log like [name:" ",desc:" ",.....].
 - [ ] Also, form validators are not working properly, next button should work only when that form section inputs are valid.

**Comment by raksh543** [comment]
@AasthaSinha2305 Please complete the requested changes.

**Comment by AasthaSinha2305** [comment]
ill make a new pull request

**Pull request closed without merging**
