### PR TITLE
FAQ page added

### PR DESCRIPTION
**Pull request by vikhyatsingh123**

### CODE REVIEW

**Review by rishabhborn2win — CHANGES_REQUESTED** [review]
Just add node-sass in the dependencies 

Using:-
npm i node-sass --save

**Review by raksh543 — CHANGES_REQUESTED** [review]
@vikhyatsingh123 Please do the required changes to pass all the checks.

**Comment by vikhyatsingh123** [comment]
@rishabhborn2win By using npm i node-sass --save, I got node_modules and package-lock.json file. So, where to add these files

**Comment by rishabhborn2win** [comment]
> @rishabhborn2win By using npm i node-sass --save, I got node_modules and package-lock.json file. So, where to add these file

> @rishabhborn2win By using npm i node-sass --save, I got node_modules and package-lock.json file. So, where to add these files

You have done everything right the only thing you did wrong is the commit the node-modules folder and package-lock.json file just revert your commit to a006ebc then also it will also pass all the checks

**Comment by rishabhborn2win** [comment]
> @rishabhborn2win By using npm i node-sass --save, I got node_modules and package-lock.json file. So, where to add these files

You are not required to add those files that files are ignored.

**Comment by rishabhborn2win** [comment]
You are required to merge your branch with the upstream branch of the base repo.

**Review by rishabhborn2win — CHANGES_REQUESTED** [review]
Please update your styling for differenent and unique className as max of the className are of BOOTSTRAP so its affecting others component too.

**Pull request closed without merging**
